version: '3.8'

services:
  # Servicio de Autenticación y Usuarios
  auth_user_service:
    build:
      context: ./auth_user_service
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql://root:password@mysql:3306/auth_db
      - JWT_SECRET=your_jwt_secret_key
      - JWT_ALGORITHM=HS256
      - JWT_EXPIRATION=3600
    volumes:
      - ./auth_user_service:/app
    depends_on:
      - mysql
    networks:
      - courseclash-network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # Servicio de Cursos
  course_service:
    build:
      context: ./course_service
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=mysql://root:password@mysql:3306/course_db
      - JWT_SECRET=your_jwt_secret_key
    volumes:
      - ./course_service:/app
    depends_on:
      - mysql
    networks:
      - courseclash-network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload

  # Servicio de Duelos
  duel_service:
    build:
      context: ./duel_service
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/duel_db
    depends_on:
      - mongo
    networks:
      - courseclash-network

  # API Gateway
  api_gateway:
    build:
      context: ./api_gateway
    ports:
      - "8080:8080"
    environment:
      - AUTH_SERVICE_URL=http://auth_user_service:8000
      - COURSE_SERVICE_URL=http://course_service:8001
      - DUEL_SERVICE_URL=http://duel_service:8002
      - JWT_SECRET=your_jwt_secret_key
    volumes:
      - ./api_gateway:/app
    depends_on:
      - auth_user_service
      - course_service
      - duel_service
    networks:
      - courseclash-network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload

  # Frontend
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - api_gateway
    networks:
      - courseclash-network
    command: npm run dev -- --host 0.0.0.0

  # Base de datos MySQL (para auth_user_service y course_service)
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=auth_db
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-scripts/mysql:/docker-entrypoint-initdb.d
    networks:
      - courseclash-network
    command: --default-authentication-plugin=mysql_native_password

  # Base de datos MongoDB (para duel_service)
  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - courseclash-network

volumes:
  mysql_data:
  mongo_data:

networks:
  courseclash-network:
    driver: bridge
