apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  labels:
    app: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 8080 # Puerto que usará tu cc_lb para conectarse
      targetPort: 8091 # Puerto del contenedor (donde corre uvicorn)
      name: http
  type: ClusterIP # Interno, para usar con tu cc_lb existente
